In [61]:
import numpy as np

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
z=np.arange(10,49)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [14]:
s=np.arange(9).reshape(3,3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
a=np.random.rand(3,3,3)
print(a)

[[[0.44758252 0.38308884 0.808728  ]
  [0.33752315 0.87081354 0.97841617]
  [0.4916028  0.26290097 0.34776723]]

 [[0.33078762 0.94704885 0.57702506]
  [0.13979175 0.37903831 0.60793645]
  [0.94406315 0.81920202 0.89883161]]

 [[0.77592167 0.79761214 0.07170947]
  [0.0293565  0.80871043 0.29713517]
  [0.09279232 0.99816107 0.5156411 ]]]


In [26]:
a=np.random.rand(30)
a

array([0.73468682, 0.33800882, 0.18890827, 0.98753963, 0.25856428,
       0.58619607, 0.68751125, 0.7542009 , 0.84496485, 0.37360423,
       0.46403471, 0.11505232, 0.15377969, 0.30955311, 0.47355555,
       0.47776702, 0.35912177, 0.68046879, 0.68439615, 0.36141974,
       0.12152471, 0.35364136, 0.87863559, 0.19515653, 0.44994002,
       0.96929367, 0.77571242, 0.27156895, 0.77780079, 0.84387766])

In [27]:
# 위에 전체의 평균 구하기
m=a.mean()
print(m)

0.5156828566374003


In [28]:
mid_score=[10,20,30]
final_score=[70,80,90]
total=mid_score+final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [29]:
import numpy as np

In [30]:
mid_score=np.array([10,20,30])
final_score=np.array([70,80,90])

In [31]:
total=mid_score+final_score

In [32]:
total

array([ 80, 100, 120])

In [34]:
print("시험 성적의 합계:",total)


시험 성적의 합계: [ 80 100 120]


In [38]:
print("시험 성적의 평균:",total/2)

시험 성적의 평균: [40. 50. 60.]


In [41]:
array_a=np.arange(0,10)
array_b=np.arange(0,10)
array_c=np.arange(0,10,2)

In [44]:
array_b=np.array(range(10))
print(array_b)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
array_c=np.array(range(0,10,2))
print(array_c)

[0 2 4 6 8]


In [48]:
array_c.dtype

dtype('int32')

In [52]:
array_c.itemsize

4

In [53]:
salary=np.array([220,250,230])
salary=salary+100

In [55]:
salary*2

array([640, 700, 660])

In [74]:
players=[[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [75]:
np_players=np.array(players)

In [79]:
print('몸무게가 80이이상인 선수의 정보',np_players[np_players[:,1]>=80.0])

몸무게가 80이이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [80]:
np_players

array([[170. ,  76.4],
       [183. ,  86.2],
       [171. ,  73.5],
       [176. ,  80.1]])

In [88]:
print('키가 180이이상인 선수의 정보',np_players[np_players[:,0]>=180.0])

키가 180이이상인 선수의 정보 [[183.   86.2]]


In [102]:
revenue_in_yen=[320,240,450,450,120,320,240,450,450,120,320,240,450,450,120,320,240,450,450,120,320,240,450,450,120,320,240,450,450,120]

In [103]:
yen_array=np.array(revenue_in_yen)

In [104]:
yen_array.size

30

In [105]:
won_array=yen_array*9.7


In [106]:
won_array

array([3104., 2328., 4365., 4365., 1164., 3104., 2328., 4365., 4365.,
       1164., 3104., 2328., 4365., 4365., 1164., 3104., 2328., 4365.,
       4365., 1164., 3104., 2328., 4365., 4365., 1164., 3104., 2328.,
       4365., 4365., 1164.])

In [115]:
doller_array=yen_array*1391

In [116]:
doller_array

array([445120, 333840, 625950, 625950, 166920, 445120, 333840, 625950,
       625950, 166920, 445120, 333840, 625950, 625950, 166920, 445120,
       333840, 625950, 625950, 166920, 445120, 333840, 625950, 625950,
       166920, 445120, 333840, 625950, 625950, 166920])

In [117]:
total=won_array+doller_array
total

array([445564.8, 334173.6, 626575.5, 626575.5, 167086.8, 445564.8,
       334173.6, 626575.5, 626575.5, 167086.8, 445564.8, 334173.6,
       626575.5, 626575.5, 167086.8, 445564.8, 334173.6, 626575.5,
       626575.5, 167086.8, 445564.8, 334173.6, 626575.5, 626575.5,
       167086.8, 445564.8, 334173.6, 626575.5, 626575.5, 167086.8])

In [122]:
new_array=won_array*100
new_array

array([44480., 33360., 62550., 62550., 16680., 44480., 33360., 62550.,
       62550., 16680., 44480., 33360., 62550., 62550., 16680., 44480.,
       33360., 62550., 62550., 16680., 44480., 33360., 62550., 62550.,
       16680., 44480., 33360., 62550., 62550., 16680.])

In [123]:
won_array.astype("int64")

array([444, 333, 625, 625, 166, 444, 333, 625, 625, 166, 444, 333, 625,
       625, 166, 444, 333, 625, 625, 166, 444, 333, 625, 625, 166, 444,
       333, 625, 625, 166], dtype=int64)

In [124]:
print(new_array)

[44480. 33360. 62550. 62550. 16680. 44480. 33360. 62550. 62550. 16680.
 44480. 33360. 62550. 62550. 16680. 44480. 33360. 62550. 62550. 16680.
 44480. 33360. 62550. 62550. 16680. 44480. 33360. 62550. 62550. 16680.]


In [131]:
sad_days_revenue=new_array[new_array<=50000]
sad_days_revenue

array([44480., 33360., 16680., 44480., 33360., 16680., 44480., 33360.,
       16680., 44480., 33360., 16680., 44480., 33360., 16680., 44480.,
       33360., 16680.])

# 연습
    #1부터 50까지 짝수만 원소로 갖은 넘파이 배열 생성

In [7]:
array_r=np.arange(2,51,2)
array_r

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

   - 1번0을 원소로 갖은 4*4배열 생성
   - 2번1을 원소로 갖는 10*10베열 생성
   - 3번본인이 좋아하는 숫자를 원소로 갖는 7*4배열 생성

In [9]:
#1번
arr_ex01=np.ones((10,10))
arr_ex01

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
#2번
arr_ex03=np.full((7,4),4)
arr_ex03

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [12]:
#1부터 100까지 원소중에 3의 배수를 원소로 갖는 넘파이 배열 생성
arr_ex04=np.arange(3,101,3)
arr_ex04

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

- 만들어진 3의 배수를 원소로 갖는 넘파이 배열의(원소)개수를 구하고,reshape함수를 이용하여 2차원 배열을 생성하시오
- 생성된 2차원 배열의 크기(shape)를 구하시오

In [13]:
# 개수
arr_ex04.size

33

In [17]:
arr_ex05=arr_ex04.reshape((11,3))
print(arr_ex05)


[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]
 [39 42 45]
 [48 51 54]
 [57 60 63]
 [66 69 72]
 [75 78 81]
 [84 87 90]
 [93 96 99]]


In [18]:
#배열 크기 구하기
arr_ex05.shape

(11, 3)

In [ ]:
import random

# 1.0~1사이에 값을 랜덤하게 가지는 6*4 배열을 생성하시오,
# 2.1~100 사이의 값을 랜덤하게 가지는 5*5 배열을 생성하시오
# 3.astype을 사용하여 2번의 배열을 실수 형태로의 원소를 가지는 배열로 바꾸시오

In [28]:
#1번
e=np.random.rand(6,4)
e

array([[0.63557702, 0.1578608 , 0.32511825, 0.91152864],
       [0.47089746, 0.40798423, 0.04978622, 0.70969643],
       [0.01803126, 0.08277833, 0.34544576, 0.71749724],
       [0.05389672, 0.68248928, 0.24089265, 0.72549078],
       [0.78834083, 0.96369136, 0.56688466, 0.00901211],
       [0.0820371 , 0.22130193, 0.08785787, 0.95213051]])

In [33]:
#2번
randint_arr=np.random.randint(1,100,(5,5))
randint_arr

array([[97, 44,  5,  3, 39],
       [43, 48, 39, 56, 23],
       [74, 90, 33, 59, 54],
       [92, 66,  4, 60, 54],
       [49,  6, 91, 92, 46]])

In [34]:
#3번
arr_float=randint_arr.astype('float64')
arr_float

array([[97., 44.,  5.,  3., 39.],
       [43., 48., 39., 56., 23.],
       [74., 90., 33., 59., 54.],
       [92., 66.,  4., 60., 54.],
       [49.,  6., 91., 92., 46.]])

-  주어진 배열에서 3,4,8,9 원소만 가져오기
-  주어진 배열에서 6,7,8 원소만 가져오기

In [35]:
x=np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
x[:,3:6]

array([[3, 4],
       [8, 9]])

In [39]:
x[1,1:4]

array([6, 7, 8])

In [ ]:
#1.(3,8,13)원소 가져오기
#2.(5,6,7,8,9) 원소 가져오기
#3. (1,2,3,4,5,6,7,) 원소 가져오기

In [49]:
y=np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [53]:
print(y[:,3:4])

[[ 3]
 [ 8]
 [13]]


In [55]:
y[1,:]

array([5, 6, 7, 8, 9])

In [58]:
y[:2,1:4]


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [70]:
arr2d=np.arange(1,13).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# arr2d에서 5보다 작거나 같은 값만 추출하시오

In [72]:
arr2d[arr2d <=5]


array([1, 2, 3, 4, 5])

## arr2d에서 3의 배수만 추출하기

In [75]:
arr2d[arr2d%3==0]

array([ 3,  6,  9, 12])

## &: AND
## I:OR

In [76]:
x=np.random.randint(1,100, size=10)
x

array([ 7, 30, 30, 78, 63, 40, 82,  7, 57, 56])

In [77]:
#2의 배수 추출하기
x[x%2==0]

array([30, 30, 78, 40, 82, 56])

In [78]:
#60이상 배수 추출하기
x[x>=60]

array([78, 63, 82])

- x에서 30보다 크고 70보다 작은 수만 추출하기
-  x에서 60보다 크거나 홀수인 수를 추출하기

In [80]:
x[(x<70)&(x>30)]


array([63, 40, 57, 56])

In [86]:
x[(x>60)|(x%2!=0)]

array([ 7, 78, 63, 82,  7, 57])

In [84]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
        24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [85]:
len(temp)

31

- 예제)2019년 7월 서울 기온 데이터
 - 기온이 25도를 넘는 날 수?
 - 기온이 25도를 넘는 날의 평균 기온은?

In [87]:
len(temp[temp>25.0])

21

In [88]:
temp>25.0

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [89]:
np.sum(temp>25.0)

21

In [90]:
temp[temp>25.0]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [91]:
# 평균 기온 구하기
np.mean(temp[temp>25.0])

26.857142857142858

# 정렬:sort  은 저장이 안되뮤ㅠ

In [93]:
#-1차원 정렬은 매우 간단
arr= np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [94]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [95]:
np.sort([1,10,5,8,2,4,3,6,8,7,9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [96]:
np.sort(arr)[::-1] #내림차순 정렬 암기?!

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [101]:
arr2=np.sort([1,10,5,8,2,4,3,6,8,7,9])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 2.N차원 정렬

In [102]:

arr2d=np.array([[5,6,7,8],
                [4,3,2,1],
              [10,9,12,11]])

In [103]:
arr2d.shape

(3, 4)

## 2-1 열 정렬(왼쪽에서 오른쪽으로)

In [107]:

np.sort(arr2d,axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## 2-2, 행 정렬(위에서 아래로)

In [108]:
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [109]:
y=np.random.randint(100,size=(3,5))
print(y)

[[82 75 88 69 40]
 [57 98 78 80 54]
 [81 36 39 79 10]]


-  y 원소들의 평균, 합 ,최대값,분산,표준편차를 구해봅시다.

In [111]:
np.mean(y)

64.4

In [112]:
y.mean()

64.4

In [114]:
y.max()

98

In [115]:
y.sum()

966

In [116]:
y.min()

10

In [117]:
#분산
y.var()

547.7066666666667

In [119]:
#중앙값
np.median(y)

75.0

In [121]:
#표준 편차
np.std(y)

23.403133693304124