In [2]:
import numpy as np

In [3]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [5]:
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [6]:
array1= np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [8]:
arr2= np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
### 크기 확인(1차원)
array1.shape

(5,)

In [11]:
#2차원이양
arr2.shape

(2, 3)

In [13]:
print(array1)
print(array1.size)

[1 2 3 4 5]
5


In [14]:
# 사이즈 확인
print(arr2)
print(arr2.size)

[[1 2 3]
 [4 5 6]]
6


In [15]:
## dtype 확인
print(array1)
print(array1.dtype)

[1 2 3 4 5]
int32


In [16]:
print(arr2)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [17]:
#배열의 차원확인 하기 
print(array1)
print(array1.ndim)

[1 2 3 4 5]
1


In [18]:
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# 3차원을 만들어 버렷!

In [42]:
arr3=np.array([[[2,4],[3,5]],
      [[5,7] ,[7,7]]])

In [43]:
print(arr3)
print(arr3.ndim)

[[[2 4]
  [3 5]]

 [[5 7]
  [7 7]]]
3


In [41]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
arr_full= np.full((5,5),8)
arr_full

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [54]:
list=[]
for e in range(1,51):
    list.append(e)
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [56]:
arr= np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [58]:
arr=np.arange(1,51,20)
arr

array([ 1, 21, 41])

In [59]:
arr=np.random.rand(2,3)
arr

array([[0.63593946, 0.85020069, 0.01550219],
       [0.9775104 , 0.82979474, 0.43302743]])

In [60]:
arr=np.random.randint(2,10)
arr

8

In [98]:
arr= np.random.randint(2,10,size=(2,3))
arr

array([[9, 8, 7],
       [5, 7, 8]])

In [101]:
#타입 지정해서 배열하기
arr_type=np.array([1.2,2.3,3.4],dtype=np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [102]:
arr_type= arr_type.astype("float64")
arr_type

array([1., 2., 3.])

In [105]:
arr_type.dtype

dtype('float64')

In [106]:
#array 연산(요소별 연산)

In [108]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [110]:
arr+arr

array([2, 4, 6])

In [111]:
arr*arr

array([1, 4, 9])

In [ ]:
## 2차원 배열

In [114]:
arr_a=np.array([[1,2,3],
              [4,5,6]])
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
arr_b= np.array([[7,8,9],[10,11,12]])
arr_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [118]:
arr_a+3

array([[4, 5, 6],
       [7, 8, 9]])

In [119]:
arr_b*5

array([[35, 40, 45],
       [50, 55, 60]])

## 인덱싱과 슬라이싱

In [ ]:
# arrary 인덱싱(1차원 배열)

In [120]:
arr_1=np.array([0,1,2,3,4,5])
arr_1

array([0, 1, 2, 3, 4, 5])

In [127]:
arr_1[2]

2

In [130]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [131]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
arr[1][0]

4

In [136]:
arr[1][2]

6

In [137]:
arr[1]

array([4, 5, 6])

In [139]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
arr1[3:8]

array([3, 4, 5, 6, 7])

In [143]:
arr1[3:8]=12

In [144]:
arr1

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [145]:
#2차원 array 생성
arr2=np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [150]:
#2차원 슬레이싱
arr2[:2:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [151]:
arr2[:,0]

array([ 0, 10, 20, 30, 40])

In [162]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [175]:
arr2[4,8]

48

In [176]:
arr2[2,9]

29

In [177]:
arr2[1,2]

12

## BOOlean 색인

In [179]:
score=np.array([80,75,55,96,30])
score

array([80, 75, 55, 96, 30])

In [180]:
score>80

array([False, False, False,  True, False])

In [181]:
score[score>=80]

array([80, 96])

In [184]:
name2= np.array(["영화","동원",'성우',"수민"])
name2

array(['영화', '동원', '성우', '수민'], dtype='<U2')

In [186]:
bol= np.array([False, True, False,True])
bol

array([False,  True, False,  True])

In [187]:
name[bol]

array(['동원', '수민'], dtype='<U2')